# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(939, 501)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("r.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_5 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(4)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.text_textEdit = QtGui.QTextEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.text_textEdit.sizePolicy().hasHeightForWidth())
        self.text_textEdit.setSizePolicy(sizePolicy)
        self.text_textEdit.setObjectName(_fromUtf8("text_textEdit"))
        self.verticalLayout.addWidget(self.text_textEdit)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_16.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.pushButton_use = QtGui.QPushButton(Dialog)
        self.pushButton_use.setObjectName(_fromUtf8("pushButton_use"))
        self.horizontalLayout_16.addWidget(self.pushButton_use)
        self.pushButton_revoke = QtGui.QPushButton(Dialog)
        self.pushButton_revoke.setObjectName(_fromUtf8("pushButton_revoke"))
        self.horizontalLayout_16.addWidget(self.pushButton_revoke)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.return_textEdit = QtGui.QTextEdit(Dialog)
        self.return_textEdit.setObjectName(_fromUtf8("return_textEdit"))
        self.verticalLayout.addWidget(self.return_textEdit)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(3, 1)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioButton_all_replace = QtGui.QRadioButton(Dialog)
        self.radioButton_all_replace.setChecked(True)
        self.radioButton_all_replace.setAutoExclusive(False)
        self.radioButton_all_replace.setObjectName(_fromUtf8("radioButton_all_replace"))
        self.horizontalLayout_2.addWidget(self.radioButton_all_replace)
        self.lineEdit_all_replace_old = QtGui.QLineEdit(Dialog)
        self.lineEdit_all_replace_old.setObjectName(_fromUtf8("lineEdit_all_replace_old"))
        self.horizontalLayout_2.addWidget(self.lineEdit_all_replace_old)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_all_replace_new = QtGui.QLineEdit(Dialog)
        self.lineEdit_all_replace_new.setObjectName(_fromUtf8("lineEdit_all_replace_new"))
        self.horizontalLayout_2.addWidget(self.lineEdit_all_replace_new)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButton_line_replace = QtGui.QRadioButton(Dialog)
        self.radioButton_line_replace.setAutoExclusive(False)
        self.radioButton_line_replace.setObjectName(_fromUtf8("radioButton_line_replace"))
        self.horizontalLayout_3.addWidget(self.radioButton_line_replace)
        self.lineEdit_line_old = QtGui.QLineEdit(Dialog)
        self.lineEdit_line_old.setObjectName(_fromUtf8("lineEdit_line_old"))
        self.horizontalLayout_3.addWidget(self.lineEdit_line_old)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_line_new = QtGui.QLineEdit(Dialog)
        self.lineEdit_line_new.setObjectName(_fromUtf8("lineEdit_line_new"))
        self.horizontalLayout_3.addWidget(self.lineEdit_line_new)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_10.addWidget(self.label_8)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButton_add_last = QtGui.QRadioButton(Dialog)
        self.radioButton_add_last.setChecked(False)
        self.radioButton_add_last.setAutoExclusive(False)
        self.radioButton_add_last.setObjectName(_fromUtf8("radioButton_add_last"))
        self.horizontalLayout_4.addWidget(self.radioButton_add_last)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.radioButton_add_replace = QtGui.QRadioButton(Dialog)
        self.radioButton_add_replace.setAutoExclusive(False)
        self.radioButton_add_replace.setObjectName(_fromUtf8("radioButton_add_replace"))
        self.horizontalLayout_5.addWidget(self.radioButton_add_replace)
        self.lineEdit_line_replace_char = QtGui.QLineEdit(Dialog)
        self.lineEdit_line_replace_char.setObjectName(_fromUtf8("lineEdit_line_replace_char"))
        self.horizontalLayout_5.addWidget(self.lineEdit_line_replace_char)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButton_TorF = QtGui.QRadioButton(Dialog)
        self.radioButton_TorF.setAutoExclusive(False)
        self.radioButton_TorF.setObjectName(_fromUtf8("radioButton_TorF"))
        self.horizontalLayout.addWidget(self.radioButton_TorF)
        self.checkBox_TF_all_same = QtGui.QCheckBox(Dialog)
        self.checkBox_TF_all_same.setAutoExclusive(False)
        self.checkBox_TF_all_same.setObjectName(_fromUtf8("checkBox_TF_all_same"))
        self.horizontalLayout.addWidget(self.checkBox_TF_all_same)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.radioButton_LorR = QtGui.QRadioButton(Dialog)
        self.radioButton_LorR.setAutoExclusive(False)
        self.radioButton_LorR.setObjectName(_fromUtf8("radioButton_LorR"))
        self.horizontalLayout_6.addWidget(self.radioButton_LorR)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.radioButton_deleate_head = QtGui.QRadioButton(Dialog)
        self.radioButton_deleate_head.setAutoExclusive(False)
        self.radioButton_deleate_head.setObjectName(_fromUtf8("radioButton_deleate_head"))
        self.horizontalLayout_13.addWidget(self.radioButton_deleate_head)
        self.radioButton_deleate_back = QtGui.QRadioButton(Dialog)
        self.radioButton_deleate_back.setAutoExclusive(False)
        self.radioButton_deleate_back.setObjectName(_fromUtf8("radioButton_deleate_back"))
        self.horizontalLayout_13.addWidget(self.radioButton_deleate_back)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.radioButton_add_head = QtGui.QRadioButton(Dialog)
        self.radioButton_add_head.setAutoExclusive(False)
        self.radioButton_add_head.setObjectName(_fromUtf8("radioButton_add_head"))
        self.horizontalLayout_14.addWidget(self.radioButton_add_head)
        self.radioButton_add_end = QtGui.QRadioButton(Dialog)
        self.radioButton_add_end.setAutoExclusive(False)
        self.radioButton_add_end.setObjectName(_fromUtf8("radioButton_add_end"))
        self.horizontalLayout_14.addWidget(self.radioButton_add_end)
        self.lineEdit_add_key = QtGui.QLineEdit(Dialog)
        self.lineEdit_add_key.setObjectName(_fromUtf8("lineEdit_add_key"))
        self.horizontalLayout_14.addWidget(self.lineEdit_add_key)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.radioButton_beautiful_code = QtGui.QRadioButton(Dialog)
        self.radioButton_beautiful_code.setAutoExclusive(False)
        self.radioButton_beautiful_code.setObjectName(_fromUtf8("radioButton_beautiful_code"))
        self.horizontalLayout_15.addWidget(self.radioButton_beautiful_code)
        self.lineEdit_beautiful_code_key = QtGui.QLineEdit(Dialog)
        self.lineEdit_beautiful_code_key.setObjectName(_fromUtf8("lineEdit_beautiful_code_key"))
        self.horizontalLayout_15.addWidget(self.lineEdit_beautiful_code_key)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.radioButton_beautiful_end = QtGui.QRadioButton(Dialog)
        self.radioButton_beautiful_end.setObjectName(_fromUtf8("radioButton_beautiful_end"))
        self.verticalLayout_2.addWidget(self.radioButton_beautiful_end)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.radioButton_ai_replace = QtGui.QRadioButton(Dialog)
        self.radioButton_ai_replace.setAutoExclusive(False)
        self.radioButton_ai_replace.setObjectName(_fromUtf8("radioButton_ai_replace"))
        self.horizontalLayout_7.addWidget(self.radioButton_ai_replace)
        self.lineEdit_ai_old = QtGui.QLineEdit(Dialog)
        self.lineEdit_ai_old.setObjectName(_fromUtf8("lineEdit_ai_old"))
        self.horizontalLayout_7.addWidget(self.lineEdit_ai_old)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lineEdit_ai_new = QtGui.QLineEdit(Dialog)
        self.lineEdit_ai_new.setObjectName(_fromUtf8("lineEdit_ai_new"))
        self.horizontalLayout_7.addWidget(self.lineEdit_ai_new)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_11.addWidget(self.label_9)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.radioButton_ai_add_last = QtGui.QRadioButton(Dialog)
        self.radioButton_ai_add_last.setChecked(False)
        self.radioButton_ai_add_last.setAutoExclusive(False)
        self.radioButton_ai_add_last.setObjectName(_fromUtf8("radioButton_ai_add_last"))
        self.horizontalLayout_9.addWidget(self.radioButton_ai_add_last)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.radioButton_ai_add_replace = QtGui.QRadioButton(Dialog)
        self.radioButton_ai_add_replace.setAutoExclusive(False)
        self.radioButton_ai_add_replace.setObjectName(_fromUtf8("radioButton_ai_add_replace"))
        self.horizontalLayout_8.addWidget(self.radioButton_ai_add_replace)
        self.lineEdit_ai_replace_char = QtGui.QLineEdit(Dialog)
        self.lineEdit_ai_replace_char.setObjectName(_fromUtf8("lineEdit_ai_replace_char"))
        self.horizontalLayout_8.addWidget(self.lineEdit_ai_replace_char)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.run_button = QtGui.QPushButton(Dialog)
        self.run_button.setStyleSheet(_fromUtf8("color:blue"))
        self.run_button.setObjectName(_fromUtf8("run_button"))
        self.verticalLayout_2.addWidget(self.run_button)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "复式代码编辑器v1.2.0.0", None))
        self.label.setText(_translate("Dialog", "原文：", None))
        self.label_2.setText(_translate("Dialog", "结果：", None))
        self.pushButton_use.setToolTip(_translate("Dialog", "结果作为原文", None))
        self.pushButton_use.setText(_translate("Dialog", "↑↑", None))
        self.pushButton_revoke.setToolTip(_translate("Dialog", "撤销作为原文操作", None))
        self.pushButton_revoke.setText(_translate("Dialog", "☇", None))
        self.radioButton_all_replace.setText(_translate("Dialog", "全部替换", None))
        self.label_3.setText(_translate("Dialog", "→", None))
        self.radioButton_line_replace.setText(_translate("Dialog", "逐行替换", None))
        self.label_4.setText(_translate("Dialog", "→", None))
        self.radioButton_add_last.setText(_translate("Dialog", "【追加】 末尾追加自增数", None))
        self.radioButton_add_replace.setToolTip(_translate("Dialog", "<html><head/><body><p>例如：</p><p>原文: </p><p>abcdef</p><p>abcdef</p><p>abcdef</p><p>关键字 cd  →  新关键字 xxx@num@xxx</p><p>结果会是（新关键字里的@num@会变成自增数）</p><p>abxxx1xxxef</p><p>abxxx2xxxef </p><p>abxxx3xxxef </p></body></html>", None))
        self.radioButton_add_replace.setText(_translate("Dialog", "【指代】 新关键字里的", None))
        self.lineEdit_line_replace_char.setText(_translate("Dialog", "@num@", None))
        self.label_5.setText(_translate("Dialog", "指代自增数", None))
        self.radioButton_TorF.setText(_translate("Dialog", "True/False翻转", None))
        self.checkBox_TF_all_same.setText(_translate("Dialog", "全词匹配", None))
        self.radioButton_LorR.setText(_translate("Dialog", "等号左右置换", None))
        self.radioButton_deleate_head.setText(_translate("Dialog", "清除开头空白", None))
        self.radioButton_deleate_back.setText(_translate("Dialog", "清除末尾空白", None))
        self.radioButton_add_head.setText(_translate("Dialog", "每行开头追加", None))
        self.radioButton_add_end.setText(_translate("Dialog", "每行末尾追加", None))
        self.radioButton_beautiful_code.setText(_translate("Dialog", "符号对齐（多个符号用空格分割）", None))
        self.radioButton_beautiful_end.setText(_translate("Dialog", "末尾空格对齐", None))
        self.radioButton_ai_replace.setText(_translate("Dialog", "智能替换", None))
        self.label_6.setText(_translate("Dialog", "→", None))
        self.radioButton_ai_add_last.setText(_translate("Dialog", "【追加】 末尾追加自增数", None))
        self.radioButton_ai_add_replace.setText(_translate("Dialog", "【指代】 字符串", None))
        self.lineEdit_ai_replace_char.setText(_translate("Dialog", "@num@", None))
        self.label_7.setText(_translate("Dialog", "指代自增数", None))
        self.run_button.setText(_translate("Dialog", "运行", None))

